### ISSUE TITLE
ALERT #### Discontinued *** Looking for Successor ***

### ISSUE THREAD

**Issue by itinance** [itinance/react-native-fs#1115]
Dear community

when I [took over](https://github.com/itinance/react-native-fs/issues/276) this fantastic library in April 2017, I was deep in react-native and used this library a lot in all our projects.
However, time flew by and in the meanwhile I do complete different things. I could not even catch up with latest react-native changes and thus any check of Pull Requests is hard to maintain for me.

This library and you guys deserve active maintainers and thus I will ask here: who will take over? 
How can we do this in order to achieve a trustworthy transition to a new maintainer?

The original author of react-native-js, @johanneslumpe, [told me](https://github.com/itinance/react-native-fs/issues/276#issuecomment-291981233) in 2017: _"but it would be nice if original credit would remain in place somehow. "_ So this would be a condition that should be considered with respect to Johannes. :) 

I'd like to hear your opinion how to proceed here.

Last but not least I want to say thank you for all contributions and helpful discussions. And also for any ping that was necessary in order to get latest PRs finally merged :) (Sorry for any inconvinience).

**Comment by SheetJSDev** [comment]
There are two general issues with the current state of RNFS:

1) RN core `Blob` and `fetch` support has improved quite a bit since the library inception.  There is better support for `ArrayBuffer` and typed arrays like `Uint8Array`.

Some of the original decisions should be revisited.  For example, a 2022 RNFS might implement `readFile` to return a Uint8Array by default (similar to how Deno.readFileSync works) or return an encoded string if an encoding is specified.

2) RNFS grew past the original scope.  Looking back to the beginning, as the name suggests `react-native-fs` sought to implement `fs` features (the first commit implemented a simple `readFile` and `stat`).

Now it also includes download features, some of which overlaps with RN core `fetch`.

.

It would

**Comment by birdofpreyru** [comment]
Hi @itinance, I want to take over this library.

I am the guy behind [@dr.pogodin/react-native-static-server](https://www.npmjs.com/package/@dr.pogodin/react-native-static-server), and my primary motivation for taking over this one is that I depend on it in the aforementioned **rn-static-server**, and in a number of my other projects, and the lack of maintenance here start causing me troubles.

My pitch is this &mdash; I'll make sure the library works well with the latest RN, using the new architecture, with the backward compatibility with the old architecture. Android / iOS / macOS Catalyst / Windows will be supported. All dependencies will be kept up-to-date. The codebase will be changed to follow [create-react-native-library](https://www.npmjs.com/package/create-react-native-library) template. The credits for original authors and maintainers sure will be kept.

**Comment by itinance** [comment]
Hi @birdofpreyru, I was on a retreat without any mobile connection, hence no internet, no github. I just saw your take. Let's discuss further in #1197
