### ISSUE TITLE
My DocumentDirectoryPath returns /data/data

### ISSUE THREAD

**Issue by PimDeWitte** [itinance/react-native-fs#135]
/data/data/org.missingmaps.mapswipe/files

Instead of /Android/data/org.missingmaps.mapswipe/files

How should I go about fixing this? :-)

Cheers

**Comment by xitaoque** [comment]
why do you need it to be /Android/data/org.missingmaps.mapswipe/files?
Isn't it enough that you get a directory where you can store and accept your files?

**Comment by PimDeWitte** [comment]
I already got it. I was just missing the file://. Will close when I get to
pc

**Comment by JAStanton** [comment]
RIP @PimDeWitte ... he never made it back to his pc to close this issue ;)

BTW just to clarify the issue for anyone else, `/data/data/` isn't a bug thats a real file path on the device. Also when saving a file do it like so:
```js
/* /data/data/com.app.bundleId/cache/9c4bb804-df80-4fec-bc76-3b2de49f06b8.png */
const uri = `${RNFS.CachesDirectoryPath}/${uuid.v4()}.png`;
await RNFS.writeFile(uri, b64, 'base64');
```

And if you need to access the file again, say upload the file with `fetch`, you will need to prepend the `uri` with `file://`

Also another big gotcha for me was that a base-64 string prepended with `data:image/png;base64,` is considered a malformed and will be written to file as 0 bytes but otherwise look like it'll succeed (atleast on iOS). 

^^^^^ IMO the documentation should be updated with the above explanation ^^^^^

**Comment by PimDeWitte** [comment]
Sorry, the file:// fixed it!!
