### ISSUE TITLE
All the methods in Android are slow

### ISSUE THREAD

**Issue by jerson** [itinance/react-native-fs#149]
in iOS all the react method are executed in a different thread, but in Android no 

check the docks here 

https://facebook.github.io/react-native/docs/native-modules-android.html

> Native modules should not have any assumptions about what thread they are being called on, as the current assignment is subject to change in the future. If a blocking call is required, the heavy work should be dispatched to an internally managed worker thread, and any callbacks distributed from there.

**Comment by cjdell** [comment]
I actually knew this but had forgotten. :-) The downloader on Android was made to run on its own thread because this was an obvious problem. The other methods however normally run inside a few milliseconds so not quite so obvious, unless someone is attempting to write a huge base64 string. This problem could be solved by wrapping all the Android methods like this:

```java
new Thread(new Runnable() {
  public void run() {
    // do stuff
  }
}).start();
```

Once we have V2 out I will look at doing this.
