### ISSUE TITLE
App crashes on file read

### ISSUE THREAD

**Issue by stobe1** [itinance/react-native-fs#224]
Experiencing app crash on large file size(~15s+ video) read. 
http://i.imgur.com/gxrzF4Z.png
```
RNFS.readFile(path, 'base64').then((data) => {
		data = `data:${contentType}/${type};base64,${data}`;
		fetchMessage(...);
	});
}
```
any idea how i can work around that?

**Comment by grylance** [comment]
+1

**Comment by ruler47** [comment]
+1

**Comment by etiennewaldron** [comment]
Same here

**Comment by itinance** [comment]
The issue here is that the file would remain completely in memory as base64 and the success of those operations depends on the available memory in your device.

Apart from that, with base64-encoding the memory consumption [will be 4/3](http://stackoverflow.com/a/4715480/1397160) from the original filesize. 

**That's why you shouldn't never ever load big files into memory** wether with RN/JavaScript nor in native code. For playing audio files use [react-native-sound](https://github.com/zmxv/react-native-sound) instead that streams the audiofile from a filename with native counterparts without loading it into memory once.

Just to name it: we can't do anything here. If you load 50 MB e.g. into memory while only 43 MB are still free, then those things will happen

**Comment by NelGarbuzova** [comment]
@itinance can you please tell, how to know, if file is too big for device's memory? 

For example, if user chooses file from device, how can we check if it's too big for memory of current device. To not specify an exact valid size of file, but to set it depending on the memory of current device. Is it possible?
