### ISSUE TITLE
How to save the pictures to the album on iOS?

### ISSUE THREAD

**Issue by 1556173267** [itinance/react-native-fs#281]
I want save the pictures to the album on iOS.But i don't know what's the filepath of the photo album

**Comment by itinance** [comment]
Currently this is out of scope of this library because there is no specific path to the photo album. On iOS you need a special function [UIImageWriteToSavedPhotosAlbum](https://developer.apple.com/reference/uikit/1619125-uiimagewritetosavedphotosalbum?language=objc) to achieve this and i would rather expect this from a photo/camera-related library.

**Comment by 1556173267** [comment]
@itinance Thank you for your help。I solved this problem, on iOS I used `CameraRoll.saveToCameraRoll`  save image to photo album。

**Comment by itinance** [comment]
Thanks for your feedback!

**Comment by flyskywhy** [comment]
> @itinance Thank you for your help。I solved this problem, on iOS I used `CameraRoll.saveToCameraRoll` save image to photo album。

The picture by `CameraRoll.saveToCameraRoll` is more blurry, I think the better solution is https://github.com/itinance/react-native-fs/issues/268#issuecomment-1050459606
