### ISSUE TITLE
Error in ios: Cannot read property 'RNFSFileTypeRegular' of undefined

### ISSUE THREAD

**Issue by SoorajChandran** [itinance/react-native-fs#299]
Trying to set up react-native-fs in my project. Followed the readme in exact same way. But on starting up gives me the following error. Could not find any such problem that was reported before. 
<img width="360" alt="screen shot 2017-05-27 at 2 30 41 pm" src="https://cloud.githubusercontent.com/assets/10363633/26523725/a66dd91a-433a-11e7-985a-6454e66ed25d.png">

Something to do with node_modules?

**Comment by AhmedHashemNTS** [comment]
delete node_modules folder and hit npm install will fix it

**Comment by SirNeuman** [comment]
Are you sure you did the `react-native link react-native-fs` step when adding this to your project? I was getting this same error as well until I looked back at that step in the docs and realized I forgot to do that.

**Comment by liujett** [comment]
add      import com.rnfs.RNFSPackage;      and     new RNFSPackage()    in MainApplication.java in your project

**Comment by SoorajChandran** [comment]
@AhmedHashemNTS I already tried that, still, fails. 
@SirNeuman Yes, I already ran the linking part. But it acts like as if the linking never happened. Totally clueless. have been searching all over the internet for weeks now.

**Comment by SoorajChandran** [comment]
@liujett I'm running the ios part alone now.

**Comment by cesarve77** [comment]
any update?

**Comment by kukuandroid** [comment]
Hi, just run the react-native run-android first before u reload the js because it contains native modules that was not installed yet..

**Comment by itinance** [comment]
Closed due to inactivity. Basically it is a setup issue. Please follow the installation-section in README wisely.

**Comment by kaxline** [comment]
Since the README makes it sound like you could do one of the three options for iOS (Adding automatically, adding with Cocoapods, adding manually), I started debugging problems with using the first two options instead of trying all three. Finally I tried the manual setup and that worked when nothing else did.

**Comment by wuyic** [comment]
you can exit your simulator , and  run :   react-native run-ios

**Comment by 0mkara** [comment]
It only worked once I followed manually adding steps from instructions.

**Comment by NelGarbuzova** [comment]
Same problem. for Android

**Comment by arthurpankiewicz** [comment]
@itinance A poorly written README leads to these problems

**Comment by itinance** [comment]
@arthurpankiewicz do you have any suggestions how to describe it better? in my oppinion everything was said, but since i am familiar with native iOS and android development, many steps happen automatically :) Please feel free to submit a pullrequest with installation instructions, that are more suitable for beginners.

**Comment by arthurpankiewicz** [comment]
@itinance The iOS instructions read as if you could do any of the following options - I think it should be made clear that they are all required
