### ISSUE TITLE
Can we get file name by passing uri to RNFS?

### ISSUE THREAD

**Issue by JohnRyanTsai** [itinance/react-native-fs#432]

**Comment by est7** [comment]
let filename = uri.substring(uri.lastIndexOf('/') + 1, uri.length())

**Comment by dwilt** [comment]
@JohnRyanTsai I'm assuming you're asking this because you want to be able to upload files right? I'm confused why there is not a native methods for this and we would need to use something like what @est7 suggested above. Specifically regarding [uploadFiles](https://github.com/itinance/react-native-fs#file-upload-ios-only), I'm surprised that we have to pass the filename, and not just the file path, if the logic to deduce the filename is really that simple.

**Comment by cauyyl** [comment]
> let filename = uri.substring(uri.lastIndexOf('/') + 1, uri.length())

let filename = uri.substring(uri.lastIndexOf('/') + 1, uri.length)

**Comment by instanceof-inf** [comment]
This is not a comprehensive solution, because what if the uri ends with something other than the exact filename, for example: 'filename.pdf?id=83743949&expires=1626683634'? Then the file system won't recognise it as a pdf file, in this example I used...

**Comment by instanceof-inf** [comment]
> This is not a comprehensive solution, because what if the uri ends with something other than the exact filename, for example: 'filename.pdf?id=83743949&expires=1626683634'? Then the file system won't recognise it as a pdf file, in this example I used...

In other words, what if there are query parameters behind the filename?

**Comment by anshuman** [comment]
<img width="362" alt="Screenshot 2022-03-15 at 12 01 02 PM" src="https://user-images.githubusercontent.com/21060900/158320503-d0156918-fb08-40f6-b7c8-365e4e537d6c.png">
