### ISSUE TITLE
#hash() does not do normalizeFilePath

### ISSUE THREAD

**Issue by alexey-pelykh** [itinance/react-native-fs#449]
https://github.com/itinance/react-native-fs/blob/master/FS.common.js#L328 fails with "file://..." paths

**Comment by itinance** [comment]
Thanks for reporting! Most likely a `normalizeFilePath(filepath)` would solve this issue in Line [https://github.com/itinance/react-native-fs/blob/master/FS.common.js#L328](https://github.com/itinance/react-native-fs/blob/master/FS.common.js#L328)

Is anyone willing to provide a PR? Otherwise i will fix it later by myself

**Comment by alexey-pelykh** [comment]
@itinance #450

**Comment by itinance** [comment]
Just released with 2.9.11. 
Thank you!
