### ISSUE TITLE
Android Build failing in RN 0.59.8

### ISSUE THREAD

**Issue by Udbhav12** [itinance/react-native-fs#686]
RNFS Version : 2.13.3

RN Version : 0.59.8

I recently upgraded RN version to 0.59.8 and `react-native-run-android` command fails 

I am getting the below error message

`/node_modules/react-native-fs/android/src/main/java/com/rnfs/RNFSManager.java:11: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/udbhavgoyal/Desktop/codebase/fareye-react/node_modules/react-native-fs/android/src/main/java/com/rnfs/RNFSManager.java:624: error: cannot find symbol
  private void sendEvent(ReactContext reactContext, String eventName, @Nullable WritableMap params) {
                                                                       ^
  symbol:   class Nullable
  location: class RNFSManager
Note: /Users/udbhavgoyal/Desktop/codebase/fareye-react/node_modules/react-native-fs/android/src/main/java/com/rnfs/RNFSManager.java uses or overrides a deprecated API.`

**Comment by stanislavgalin** [comment]
The same problem.

**Comment by hardikfareye** [comment]
I am facing the same problem

**Comment by niteshsingh0129** [comment]
The same problem !!

**Comment by rahul-algorithmgeek** [comment]
Yes Its an issue.

**Comment by quantb95** [comment]
Same problem . Anyone fix ?

**Comment by brendanosborne** [comment]
Same.

**Comment by Frank-vdm** [comment]
Same here

**Comment by OliveIT** [comment]
I have that problem when I use
react-native@0.59.4
react-native-camera@2.10.0
react-native-fs@2.13.3
react-native-gesture-handler@1.1.0

I installed react-native-camera@2.9.0
And added this in android/app/build.gradle

android {
...
    defaultConfig {
...
        missingDimensionStrategy 'react-native-camera', 'general'
    }
}

It is solved.

**Comment by bthuan** [comment]
FYI, I have the same problem with RN 0.59.8, then i upgrade to 0.59.9 ( they just released 7 hour ago at the time i wrote this post) and the error is gone.

**Comment by Udbhav12** [comment]
@bthuan Thanks man! Upgrading to 0.59.9 seems to somehow fix this bug

**Comment by maieonbrix** [comment]
Can we re-open this issue ? Upgrading to 0.59.9 didn't help me at all ...

**Comment by maieonbrix** [comment]
After struggling like crazy all day long, I finally found a solution and unfortunately it is not the one provided in this issue.

Basically I started having this issue after the androidx update thing.

At first I was having issues found on the main repo like this one : https://github.com/facebook/react-native/issues/25294 
It was due to an AndroidManifest.xml file not being fully complete. I had to add this : https://github.com/facebook/react-native/issues/25294#issuecomment-503021597

Then the react-native-fs thing pops up that led me here, after trying to downgrade / upgrade in every react-native version I decided to tackle the problem at the source : if the .NonNull symbol was not found, let's find why but then this led to randomly trying package names till I found the .annotation prop which I found on the androidx package.

Then I removed the `import android.support.annotation.Nullable;` L11 from RNFSManager.java file and replaced it with : `import androidx.annotation.Nullable;` (this symbol was not greyed out / red like the previous one).

And then the error disappeared for the react-native-fs package but appeared on several other non-related packages which I managed to fix by doing the same thing.

Hope it helps someone.

**Comment by jgreen01su** [comment]
@maieonbrix Great! Thank you for the detailed explanation! I'm also having this issue after updating to `0.59.9`. I'll probably be doing the same with some of dependencies. Could you create a PR for the change you made? That way others can pull your update.

React Native is migrating to androidx and all packages will need to make the change.
https://github.com/react-native-community/discussions-and-proposals/issues/129

**Comment by jgreen01su** [comment]
@maieonbrix I created a PR. Let me know if you'd like me to take it down so you can submit your own.
https://github.com/itinance/react-native-fs/pull/691

**Comment by yusuf987** [comment]
thanks @maieonbrix your solution worked

**Comment by maieonbrix** [comment]
I think you need indeed to update each of your packages, the simplest solution right now is just to delete the import and the annotation since it is just an annotation. told by @mikehardy here : https://github.com/itinance/react-native-fs/pull/691#issuecomment-504562995

**Comment by darsodango** [comment]
@maieonbrix I tried doing your method and it's still throwing an `RNFSManager.java uses or overrides a deprecated API `

btw, my react-native version is `0.60.0` and my react-native-fs is `2.13.0`

**Comment by maieonbrix** [comment]
@darsodango you need to remove both the imports and the annotation here : https://github.com/itinance/react-native-fs/blob/v2.13.3/android/src/main/java/com/rnfs/RNFSManager.java#L624

If this doesn't work then it's a new issue so open a new one, copy past the full error and I'll gladly try to help

**Comment by wincod75** [comment]
Anyone else still getting this error? I've tried all suggested fixes/hacks, nothing is working. I've tried various version of RNFS from "2.13.2" to "2.14.0" and now "2.15.2".

Reads:

"/node_modules/react-native-fs/android/src/main/java/com/rnfs/RNFSManager.java:
uses or overrides a deprecated API.
Recompile with -Xlint:deprecation for details."

"react": "16.6.3",
"react-native": "0.58.1",
"react-native-fs": "2.15.2",

**Comment by anuj-jain-externlabs** [comment]
> @darsodango you need to remove both the imports and the annotation here : https://github.com/itinance/react-native-fs/blob/v2.13.3/android/src/main/java/com/rnfs/RNFSManager.java#L624 (delete both `import android.support.annotation.Nullable;` and the `@Nullable`).
> 
> If this doesn't work then it's a new issue so open a new one, copy past the full error and I'll gladly try to help.

i am facing an issue something like that but cann't find solution .Can you help me out ?

**Comment by juliojeronimo** [comment]
I'm getting this error inside a CI/CD application. I can't edit node_modules. Do somebody have any alternative?

**Comment by mikehardy** [comment]
@juliojeronimo you need to use jetifier either in forward or reverse mode depending on if you are using AndroidX or trying to remain on the support libraries. It will edit node_modules, if that is a hard constraint you need to talk with the people that made it in order to relax the constraint, as a practical matter.
