### ISSUE TITLE
Another bug in 2.15

### ISSUE THREAD

**Issue by StasD** [itinance/react-native-fs#788]
Issues a warning:
```
Sending `DownloadBegin` with no listeners registered.
```
when I do
```
  let {promise} = fs.downloadFile({fromUrl, toFile});
```

**Comment by StasD** [comment]
Going back to 2.14 for now...

**Comment by itinance** [comment]
@StasD 
So, it's just a `warning` and not a serious error? Will definitely have a look at it. I'm just asking to identify if its a serious issue breaking `downloadFile`

**Comment by itinance** [comment]
I think it has something to do with this PR: https://github.com/itinance/react-native-fs/pull/752

**Comment by itinance** [comment]
@jnpdx can you have a look at this issue here pls? There is little chance that it was introduced with #752

**Comment by StasD** [comment]
Also I use react-native-navigation component, which requires AppDelegate.m to be modified: [here](https://wix.github.io/react-native-navigation/#/docs/Installing?id=ios). I took a quick look at "Files changed" section of that PR and thought this information could be relevant...

**Comment by jnpdx** [comment]
@itinance 

It looks like event listeners are only registered in the event that a `begin` parameter is passed.  So, it seems that the options would be:

1) Register an empty callback with the emitter in the event that no `begin` parameter was sent.
2) Only send events with the emitter if the `begin` or similar parameters have been registered.

#1 seems like a better option because #2 will require changing the signature of the native methods in order to implement.  I'd be happy to submit a PR for #1.

However, I have a secondary issue, which is I can't actually seem to replicate this issue, whether I pass callbacks or not.

@StasD -- what versions of React Native and iOS are you on?

**Comment by StasD** [comment]
All latest: RN 0.61.2, iOS 13.1 in the simulator.

**Comment by StasD** [comment]
@itinance Also, please check out the above link from react-native-navigator documentation. I have a suspicion that the way how AppDelegate.m is modified might have something to do with this. Though I might be wrong.

**Comment by jnpdx** [comment]
@StasD Ah, I see, this issue only appears for me in certain scenarios (eg other listeners have never been registered).  Since I was testing uploads as well, I didn't see it.

It looks like the current hot fix would be to pass `() => {}` for the `begin` parameter when you call `downloadFile`.  That also supports my first fix idea I suggested above.  I'll submit a PR unless @itinance  has an issue with that method of fixing it.

**Comment by jnpdx** [comment]
@StasD alternately, try with this fork, which will become my PR if it works: https://github.com/jnpdx/react-native-fs#7558d9f

**Comment by StasD** [comment]
Yes, if I pass `() => {}` for the `begin` parameter, warnings disappear. Interestingly, the warning for `progress` disappears too...

**Comment by jnpdx** [comment]
@StasD yeah, I think that's why I didn't see this issue at first the emitter is really inconsistent about when it complains about things.  I'll submit my patch as a PR.
